CREATE TABLE public.voitures_transmission(
  id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description varchar NOT NULL,
  CONSTRAINT voitures_transmission_pkey PRIMARY KEY (id)
);

ALTER TABLE public.voitures
  ADD CONSTRAINT voiture_transmission_fk FOREIGN KEY (transmission) REFERENCES voitures_transmission(id) ON UPDATE CASCADE;

