
create table public.temoignages (
  id bigint primary key generated always as identity,
  name varchar(30) not null,
  note smallint not null,
  message varchar(250) not null,
  approved boolean not null default false,
  created_at timestamp not null default now()
);

create table public.employees (
    id uuid not null default gen_random_uuid(),
    name text not null,
    email text not null,
    password text not null default md5(random()::text),
    role smallint not null default 2, -- 1 admin, 2 employee
    created_at timestamp with time zone not null default now(),
    last_password timestamp with time zone
);


create table public.voitures (
    id uuid not null default gen_random_uuid(),
    price real not null,
    year smallint not null,
    kilometrage integer not null,
    image text not null,
    description text,
    equipment text[],
    options text[],
    created_at timestamp with time zone not null default now(),
    created_by text not null
);

create table public.contacts (
    id bigint generated by default as identity not null,
    first_name text not null,
    last_name text not null,
    email text not null,
    telephone text not null,
    message text not null,
    voiture_id uuid,
    created_at timestamp with time zone not null default now(),
    responded boolean not null default false,
    responded_by uuid
);