CREATE TABLE public.voitures(
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  price real NOT NULL,
  year smallint NOT NULL,
  kilometrage integer NOT NULL,
  image text NOT NULL,
  engine varchar(50),
  traction varchar(10),
  power int,
  doors int,
  seats int,
  transmission int,
  options text[],
  other_images text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid NOT NULL,
  CONSTRAINT voitures_pkey PRIMARY KEY (id),
  CONSTRAINT voitures_id_key UNIQUE (id),
  CONSTRAINT voitures_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON UPDATE CASCADE
);

CREATE TABLE public.contacts(
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  telephone text NOT NULL,
  message text NOT NULL,
  voiture_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  responded boolean NOT NULL DEFAULT FALSE,
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_id_key UNIQUE (id),
  CONSTRAINT contacts_voiture_id_fkey FOREIGN KEY (voiture_id) REFERENCES voitures(id) ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE temoignages
  ADD CONSTRAINT temoignages_responded_by_fkey FOREIGN KEY (approved_by) REFERENCES profiles(id) ON UPDATE CASCADE;

